import type { CanonicalInviteStatus, CanonicalUserActivityStatus, CanonicalUserRole, CanonicalUserStatus, ManageableUserRole } from "../constants/user-canonical-enums";
export type UserRole = CanonicalUserRole; export type UserStatus = CanonicalUserStatus; export type InviteStatus = CanonicalInviteStatus; export type UserActivityStatus = CanonicalUserActivityStatus;
export interface CrmUser { id: string; fullName: string; email: string; phone?: string; avatarUrl?: string; role: UserRole; roleLabel: "Super Admin" | "Sales Manager" | "Sales Agent"; teamId?: string; teamName?: string; status: UserStatus; inviteStatus: InviteStatus; activityStatus: UserActivityStatus; mustChangePassword: boolean; hasTemporaryPassword: boolean; temporaryPasswordExpiresAt?: string; accessEmailSentAt?: string; inviteAcceptedAt?: string; lastLoginAt?: string; lastActivityAt?: string; createdBy: string; createdByName: string; createdAt: string; updatedAt: string; canManage?: boolean; }
export interface CrmTeam { id: string; name: string; description?: string; managerId?: string; managerName?: string; memberCount: number; }
export interface UserFilters { search?: string; role?: UserRole | "All"; status?: UserStatus | "All"; inviteStatus?: InviteStatus | "All"; teamId?: string; activityStatus?: UserActivityStatus | "All"; }
export interface CreateUserInput { fullName: string; email: string; phone?: string; role: ManageableUserRole; teamId?: string; status: UserStatus; sendAccessEmail: boolean; temporaryPassword?: string; requirePasswordChangeOnFirstLogin: boolean; }
export interface UpdateUserInput { fullName?: string; phone?: string; role?: ManageableUserRole; teamId?: string; status?: UserStatus; }
export interface UserAuditLog { id: string; userId: string; action: "user_created" | "user_updated" | "role_changed" | "team_changed" | "status_changed" | "access_email_sent" | "password_reset" | "password_changed" | "login_success" | "login_failed"; description: string; actorUserId: string; actorName: string; createdAt: string; }
export interface UsersListResponse { data: CrmUser[]; meta: { total: number; page: number; pageSize: number; totalPages: number }; }
export interface UserDetailResponse { user: CrmUser; auditLogs: UserAuditLog[]; }
